[2024-10-16T07:06:10.138+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: db_to_offline_store.clean_task manual__2024-10-16T07:06:07.627714+00:00 [queued]>
[2024-10-16T07:06:10.269+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: db_to_offline_store.clean_task manual__2024-10-16T07:06:07.627714+00:00 [queued]>
[2024-10-16T07:06:10.269+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-10-16T07:06:10.269+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2024-10-16T07:06:10.269+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-10-16T07:06:10.282+0000] {taskinstance.py:1389} INFO - Executing <Task(DockerOperator): clean_task> on 2024-10-16 07:06:07.627714+00:00
[2024-10-16T07:06:10.287+0000] {standard_task_runner.py:52} INFO - Started process 379 to run task
[2024-10-16T07:06:10.289+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'db_to_offline_store', 'clean_task', 'manual__2024-10-16T07:06:07.627714+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline/db_to_offline_store.py', '--cfg-path', '/tmp/tmpfgfvvlvg', '--error-file', '/tmp/tmpaxjon8rh']
[2024-10-16T07:06:10.290+0000] {standard_task_runner.py:80} INFO - Job 5: Subtask clean_task
[2024-10-16T07:06:10.350+0000] {task_command.py:371} INFO - Running <TaskInstance: db_to_offline_store.clean_task manual__2024-10-16T07:06:07.627714+00:00 [running]> on host bc2dbf4723f9
[2024-10-16T07:06:10.425+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=mlopsvn
AIRFLOW_CTX_DAG_ID=db_to_offline_store
AIRFLOW_CTX_TASK_ID=clean_task
AIRFLOW_CTX_EXECUTION_DATE=2024-10-16T07:06:07.627714+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-16T07:06:07.627714+00:00
[2024-10-16T07:06:10.442+0000] {docker.py:262} INFO - Starting docker container from image mlopsvn/mlops_crash_course/data_pipeline:latest
[2024-10-16T07:06:10.446+0000] {docker.py:273} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-10-16T07:06:10.701+0000] {docker.py:324} INFO - 2024-10-16 07:06:10,701 - utils.logger - INFO - Cleaning up...
[2024-10-16T07:06:10.878+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=db_to_offline_store, task_id=clean_task, execution_date=20241016T070607, start_date=20241016T070610, end_date=20241016T070610
[2024-10-16T07:06:10.902+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-16T07:06:10.936+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
