[2024-09-23T10:25:48.352+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: db_to_offline_store.explore_and_validate_task manual__2024-09-23T10:25:45.237998+00:00 [queued]>
[2024-09-23T10:25:48.493+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: db_to_offline_store.explore_and_validate_task manual__2024-09-23T10:25:45.237998+00:00 [queued]>
[2024-09-23T10:25:48.493+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-09-23T10:25:48.493+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2024-09-23T10:25:48.493+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-09-23T10:25:48.505+0000] {taskinstance.py:1389} INFO - Executing <Task(DockerOperator): explore_and_validate_task> on 2024-09-23 10:25:45.237998+00:00
[2024-09-23T10:25:48.512+0000] {standard_task_runner.py:52} INFO - Started process 5236 to run task
[2024-09-23T10:25:48.514+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'db_to_offline_store', 'explore_and_validate_task', 'manual__2024-09-23T10:25:45.237998+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline/db_to_offline_store.py', '--cfg-path', '/tmp/tmp5dcwuhc8', '--error-file', '/tmp/tmphl4ktsix']
[2024-09-23T10:25:48.515+0000] {standard_task_runner.py:80} INFO - Job 138: Subtask explore_and_validate_task
[2024-09-23T10:25:48.569+0000] {task_command.py:371} INFO - Running <TaskInstance: db_to_offline_store.explore_and_validate_task manual__2024-09-23T10:25:45.237998+00:00 [running]> on host dc34e5e06cda
[2024-09-23T10:25:48.644+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=mlopsvn
AIRFLOW_CTX_DAG_ID=db_to_offline_store
AIRFLOW_CTX_TASK_ID=explore_and_validate_task
AIRFLOW_CTX_EXECUTION_DATE=2024-09-23T10:25:45.237998+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-23T10:25:45.237998+00:00
[2024-09-23T10:25:48.664+0000] {docker.py:262} INFO - Starting docker container from image mlopsvn/mlops_crash_course/data_pipeline:latest
[2024-09-23T10:25:48.667+0000] {docker.py:273} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-09-23T10:25:48.868+0000] {docker.py:324} INFO - 2024-09-23 10:25:48,868 - utils.logger - INFO - Exploring and validating...
[2024-09-23T10:25:49.001+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=db_to_offline_store, task_id=explore_and_validate_task, execution_date=20240923T102545, start_date=20240923T102548, end_date=20240923T102549
[2024-09-23T10:25:49.047+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-23T10:25:49.086+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
