[2024-09-23T10:08:51.196+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: db_to_offline_store.clean_task manual__2024-09-23T10:08:47.833539+00:00 [queued]>
[2024-09-23T10:08:51.364+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: db_to_offline_store.clean_task manual__2024-09-23T10:08:47.833539+00:00 [queued]>
[2024-09-23T10:08:51.364+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-09-23T10:08:51.365+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2024-09-23T10:08:51.365+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-09-23T10:08:51.380+0000] {taskinstance.py:1389} INFO - Executing <Task(DockerOperator): clean_task> on 2024-09-23 10:08:47.833539+00:00
[2024-09-23T10:08:51.385+0000] {standard_task_runner.py:52} INFO - Started process 3837 to run task
[2024-09-23T10:08:51.387+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'db_to_offline_store', 'clean_task', 'manual__2024-09-23T10:08:47.833539+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline/db_to_offline_store.py', '--cfg-path', '/tmp/tmpv6f3sfm2', '--error-file', '/tmp/tmptvxyii5p']
[2024-09-23T10:08:51.388+0000] {standard_task_runner.py:80} INFO - Job 130: Subtask clean_task
[2024-09-23T10:08:51.447+0000] {task_command.py:371} INFO - Running <TaskInstance: db_to_offline_store.clean_task manual__2024-09-23T10:08:47.833539+00:00 [running]> on host dc34e5e06cda
[2024-09-23T10:08:51.519+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=mlopsvn
AIRFLOW_CTX_DAG_ID=db_to_offline_store
AIRFLOW_CTX_TASK_ID=clean_task
AIRFLOW_CTX_EXECUTION_DATE=2024-09-23T10:08:47.833539+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-23T10:08:47.833539+00:00
[2024-09-23T10:08:51.535+0000] {docker.py:262} INFO - Starting docker container from image mlopsvn/mlops_crash_course/data_pipeline:latest
[2024-09-23T10:08:51.537+0000] {docker.py:273} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-09-23T10:08:51.736+0000] {docker.py:324} INFO - 2024-09-23 10:08:51,735 - utils.logger - INFO - Cleaning up...
[2024-09-23T10:08:51.848+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=db_to_offline_store, task_id=clean_task, execution_date=20240923T100847, start_date=20240923T100851, end_date=20240923T100851
[2024-09-23T10:08:51.880+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-23T10:08:51.917+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
